openpj
orel8654/api-serv pull request #1
Opened 2023-09-28 22:23 UTC by orel8654

2023-10-02 09:29 UTC, baibikov commented on main.go
> +	ticker := time.NewTicker(6 * time.Second)
ticker давай вынесем в конфиг (6 * time.Second)

2023-10-02 09:30 UTC, baibikov commented on main.go
> +	defer connectDB.Close()
выходит каждые N времени будешь создавать новый конект в базу ? давай использовать один коннект

2023-10-04 10:35 UTC, baibikov commented on database/queries.go
> +}
```suggestion
func (s *Storage) SelectAll() ([]config.DatabaseFields, error) {
	query := `SELECT currency_from, currency_to, well, updated_at FROM newtable`
	var res []config.DatabaseFields
	if err := s.s.Select(&res, query); err != nil {
		return res, err
	}
	return res, nil
}
```

2023-10-06 20:34 UTC, baibikov requested changes

2023-10-06 20:34 UTC, baibikov commented on config/structs.go
>  }
давай все структуры хранить лучше не в папке конфиг) а давай объявим папку types

2023-10-06 20:34 UTC, baibikov commented on handlers/app.go
> +		fmt.Println(err)
зачем этот fmt.Println(err) ?

2023-10-06 20:34 UTC, baibikov commented on handlers/app.go
> +	}
так неудобно читать

```suggestion
	err = h.db.Exists(
	    config.DataPost{
		CurrencyTo: payload.CurrencyTo,
	    },
	)
        if err != nil {
		return err
	}
```

2023-10-06 20:34 UTC, baibikov commented on ticker/tick.go
>  	}()
на данный момент функция совсем не автономная. Те мы не можем использовать эту библиотеку для чего-то помимо http запросов

2023-10-09 08:13 UTC, orel8654 commented on ticker/tick.go
>  	}()
Поправил

2023-10-09 08:15 UTC, orel8654 commented on handlers/app.go
> +		fmt.Println(err)
Это я просто смотрел что в ошибках приходит

2023-10-10 06:13 UTC, merged